--- # default for config the Firmware
- default_URL: https://firmware.darmstadt.freifunk.net
- default_Release_Model: stable
- default_Update_Type: sysupgrade
- default_FreiFunk_Verein: ffda
- default_Firmware_Version: 0.7.3